### ISSUE TITLE
after 2 rounds i get error 0 on BestStump

### ISSUE THREAD

**Issue by NicolaeStaicu** [INVASIS/Viola-Jones#1]
[Outpu.txt](https://github.com/INVASIS/Viola-Jones/files/2124786/Outpu.txt)

Above it's the console, i couldn't get a stack trace because it's not a exception it's a if from class Classifier line 211 with a system.err.println

Thank you!

**Comment by Dubrzr** [comment]
At first glance, I would say that you don't have enough training data, try with more data, or maybe deep dive into our code to find the problem, we didn't work on this since 2 years and I don't have time to find out, maybe @LorenziniUgo has?

**Comment by NicolaeStaicu** [comment]
Thanks this is what i'm trying right now, i'll let you know if it's working.
